### ISSUE TITLE
Screenshot of bookmarked page

### ISSUE THREAD

**Issue by ragloo** [p-kolacz/org-linkz#1]
Great package, congratulation.
Could it be possible to add a screenshot of the boomarked page in the org-mode file ?
Long life to your project and many thanks for sharing it.

**Comment by p-kolacz** [comment]
Thanks. I've added screenshoot to Readme. 

![screenshoot](https://user-images.githubusercontent.com/1722672/58349259-19218500-7e63-11e9-9953-e24743fd91ea.png)

**Comment by ragloo** [comment]
Nice configuration :+1: 
Sorry I was not very clear in my request I was asking if it could be possible to also add a screenshot of the bookmarked page inside the org-mode file easier browsing of the bookmarked links.
Anyway very nice setup.

**Comment by p-kolacz** [comment]
I don't think it's possible. All I can capture from browser is what JavaScript allows me to.
