### ISSUE TITLE
Offtopic question: is there a way to disable browser prompt

### ISSUE THREAD

**Issue by whudwl** [p-kolacz/org-linkz#7]
First, awesome package. Thank you.  

I started using this, but one annoying issue I found (not about this package, but about chrome/windows etc) is that whenever I use the bookmarklet, the browser would ask me to confirm that I want to open the external application to handle the protocol. There's a checkbox that says "always allow xxx.xxx.xxx to open links of this type in associated app". But it's not helpful in this case as I'd be using the bookmarklet from different pages all the time.  

Since you are definitely more experienced in using org-protocol, would you mind sharing if there's a way to disable this? 

Cheers.

**Comment by p-kolacz** [comment]
I don't use it any more, but it looks like chrome changed the way it handles external applications links. It looks like it can be fixed: https://superuser.com/questions/1481851/disable-chrome-to-ask-for-confirmation-to-open-external-application-everytime
```
[HKEY_CURRENT_USER\Software\Policies\Google\Chrome\URLWhitelist]
"1"="org-protocol://*"
```
But I did't test it.

**Comment by whudwl** [comment]
> I don't use it any more, but it looks like chrome changed the way it handles external applications links. It looks like it can be fixed: https://superuser.com/questions/1481851/disable-chrome-to-ask-for-confirmation-to-open-external-application-everytime
> 
> ```
> [HKEY_CURRENT_USER\Software\Policies\Google\Chrome\URLWhitelist]
> "1"="org-protocol://*"
> ```
> 
> But I did't test it.

Thanks for your reply. 
I did try this registry key but it did not work for me.  And I just read the documentation for this key once more at http://www.chromium.org/administrators/policy-list-3#URLWhitelist
It seems to me this key does not do what I want it to.
